#!/bin/bash
# identity
#PBS -W group_list=newriver
#PBS -A cv_fall_2017

# request resources
#PBS -l nodes=1:ppn=28
#PBS -l walltime=6:00:00:00
#PBS -q p100_normal_q

# set up email alert
#PBS -M chenhao7@vt.edu
#PBS -m bea

# Prepare environment
module purge

cd $PBS_O_WORKDIR

# Execute command

# Train only new layers with smaller set
python3 run.py vgg16 0 10
# python3 run.py resnet 0 10

# Train all layers with whole set
# python3 run.py vgg16 1 200

exit;

